config/routes.rb
Rails.application.routes.draw do

  resources :users

  get 'pages/home'

  get 'pages/contact'

  get 'pages/about'

  match '/contact', to: 'pages#contact', via: [:get]
  match '/about', to: 'pages#about', via: [:get]
  match '/signup', to: 'users#new', via: [:get]

   root 'pages#home'

end

app/models/user.rb
require 'digest'

class User < ActiveRecord::Base

	attr_accessor :password
	email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/

	validates :name, presence: true, length: {within: 5..20}
	validates :email, presence: true, format: {with: email_regex}, uniqueness: {case_sensitive: false}
	validates :password, presence: true, length: {within: 6..15}

	before_save :encrypt_password

	def has_password?(submitted_password)
		self.encrypted_password == encrypt(submitted_password)
	end

	def self.authenticate(email, password)
		user = find_by_email(email)
		return nil if user.nil?
		return user if user.has_password? password
	end

	private
		def encrypt_password
			self.salt = Time.now.utc if new_record?
			self.encrypted_password = encrypt password
		end

		def encrypt(password)
			Digest::SHA2.hexdigest "#{salt}--#{password}"
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@title = "Home"
  end

  def contact
  	@title = "Contact"
  end

  def about
  	@title = "About"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  	@title = "Sign up"
  end

  def show
  	@user = User.find(params[:id])
  	@title = @user.name
  end

  def create
  	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def title
		_title = "Twitter Spawn"
		if @title.nil?
			_title
		else
			"#{_title} | #{@title}"
		end
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user, options = { :size => 50 })
		gravatar_image_tag(user.email.downcase, :alt => user.name,
							:class => 'gravatar',
							:gravatar => options)
	end
end

app/views/layouts/_footer.html.erb
<footer>
<nav class="round">
<ul>
<li><%= link_to "About", about_path %></li>
<li><%= link_to "Contact", contact_path %></li>
</ul>
</nav>
</footer>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag 'blueprint/screen', media: 'screen' %>
<%= stylesheet_link_tag 'blueprint/print', media: 'print' %>
<%= stylesheet_link_tag 'custom', media: 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= render "layouts/stylesheets" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<header>
			<%= image_tag "logo.png", alt: "logo", class: "round"%>
			<nav class="round">
				<ul>
					<li><%= link_to "Home", root_path %></li>
					<li><%= link_to "About", about_path %></li>
					<li><%= link_to "Sign in", "#" %></li>
				</ul>
			</nav>
		</header>
		<section class="round">
			<%= yield %>	
		</section>
		<%= render "layouts/footer.html.erb" %>
		<%= debug(params) if Rails.env.development? %>
	</div>
</body>
</html>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<%= link_to "Sign Up!", "#", class: "signup_button round"%>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for(@user) do |f| %>
	<div class="field">
		<%= f.label :name %><br/>
		<%= f.text_field :name %><br/>
	</div>
	<div class="field">
		<%= f.label :email %><br/>
		<%= f.text_field :email %><br/>
	</div>
	<div class="field">
		<%= f.label :password %><br/>
		<%= f.password_field :password %><br/>
	</div>
	<div class="field">
		<%= f.label :password_confirmation, "Confirmation" %><br/>
		<%= f.password_field :password_confirmation %><br/>
	</div>
	<div class="actions">
		<%= f.submit "Sign Up" %>
	</div>
<% end %>

app/views/users/show.html.erb
<table class="profile" summary="Profile information">
<tr>
<td class="main">
<h1>
<%= gravatar_for @user %>
<%= @user.name %>
</h1>
</td>
<td class="sidebar round">
<strong>Name</strong> <%= @user.name %><br />
<strong>URL</strong> <%= link_to user_path(@user), @user %>
</td>
</tr>
</table>